ARG BASE_TAG="1.01.0"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kishoredurai/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install
ENV NVIDIA_DRIVER_CAPABILITIES=graphics,compat32,utility,compute


### Install Tools
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/install_tools_deluxe.sh  && rm -rf $INST_SCRIPTS/tools/

# Install Utilities
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/


#install shotwell

RUN apt install shotwell -y

#Install gedit
RUN apt install gedit -y

# #Install basic languages
RUN apt-get update \
    && apt-get install build-essential -y \
    && apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget 
    
    
#Install blender 
COPY ./src/ubuntu/install/blender/install_blender.sh $INST_SCRIPTS/blender/
RUN bash $INST_SCRIPTS/blender/install_blender.sh  && rm -rf $INST_SCRIPTS/blender/

# RUN apt update && sudo apt install blender -y

#Install gimp
COPY ./src/ubuntu/install/gimp $INST_SCRIPTS/gimp/
RUN bash $INST_SCRIPTS/gimp/install_gimp.sh  && rm -rf $INST_SCRIPTS/gimp/

#Install inkscape
COPY ./src/ubuntu/install/inkscape $INST_SCRIPTS/inkscape/
RUN bash $INST_SCRIPTS/inkscape/install_inkscape.sh  && rm -rf $INST_SCRIPTS/inkscape/


#install pinta
COPY ./src/ubuntu/install/pinta $INST_SCRIPTS/pinta/
RUN bash $INST_SCRIPTS/pinta/install_pinta.sh  && rm -rf $INST_SCRIPTS/pinta/

#Install scratch

RUN apt-get update \
     && apt-get install scratch -y 

#install filezilla
COPY ./src/ubuntu/install/filezilla $INST_SCRIPTS/filezilla/
RUN bash $INST_SCRIPTS/filezilla/install_filezilla.sh  && rm -rf $INST_SCRIPTS/filezilla/


# # Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/
# RUN apt-get update \
# &&  apt install firefox -y


### Install Only Office
COPY ./src/ubuntu/install/only_office $INST_SCRIPTS/only_office/
RUN bash $INST_SCRIPTS/only_office/install_only_office.sh  && rm -rf $INST_SCRIPTS/only_office/

# Install Unity
COPY ./src/ubuntu/install/unityhub $INST_SCRIPTS/unityhub/
RUN bash $INST_SCRIPTS/unityhub/install_unityhub.sh  && rm -rf $INST_SCRIPTS/unityhub/

#ADD ./src/common/scripts $STARTUPDIR
RUN $STARTUPDIR/set_user_permission.sh $HOME

RUN chown 1000:0 $HOME

ENV HOME /home/user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]
