ARG BASE_TAG="1.01.0"
ARG BASE_TAG="1.01.0"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kishoredurai/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install


### Install Tools
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/install_tools_deluxe.sh  && rm -rf $INST_SCRIPTS/tools/




# Install Utilities
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/


#install shotwell

RUN apt install shotwell -y

#Install gedit
RUN apt install gedit -y

#Install basic languages
RUN apt-get update \
    && apt-get install build-essential -y \
    && apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget 
    
# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Install Firefox
# COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
# COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
# RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

### Install Java
RUN apt-get update && apt-get install -y default-jdk default-jre


###install  snap


RUN apt-get update \
&&  apt install gnome-software -y

##Install android studio

# RUN apt-get update \
# && snap install android-studio --classic  \
# && snap install figma-linux 

#Install figma
RUN wget https://github.com/Figma-Linux/figma-linux/releases/download/v0.10.0/figma-linux_0.10.0_linux_amd64.deb \
&& sudo dpkg -i figma-linux_0.10.0_linux_amd64.deb 


#ADD ./src/common/scripts $STARTUPDIR
RUN $STARTUPDIR/set_user_permission.sh $HOME


RUN chown 1000:0 $HOME

ENV HOME /home/user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]
