name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Terminal Docker image
      run: docker build . --file dockerfile-ubuntu-terminal --tag kishoredurai/ubuntu-apps:terminal-1.01.1
    - name: Push the Terminal Docker images
      run:  docker login -u kishoredurai -p ${{ secrets.DOCKER_TOKEN }} && docker push kishoredurai/ubuntu-apps:terminal-1.01.1
